### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by ioanlongjing** [dongri/convert-to-utf8#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 14.04.2
**Thrown From**: [convert-to-utf8](https://github.com/dongri/convert-to-utf8) package, v0.2.4
### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /home/ioan/.atom/packages/convert-to-utf8/lib/convert-to-utf8.coffee:25

TypeError: Cannot read property 'getPath' of undefined
  at Object.module.exports.open (/home/ioan/.atom/packages/convert-to-utf8/lib/convert-to-utf8.coffee:25:18)
  at atom-workspace.<anonymous> (/home/ioan/.atom/packages/convert-to-utf8/lib/convert-to-utf8.coffee:14:75)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
  5x -7:23.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:49.7.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -6:37.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 convert-to-utf8:utf-8 (div.settings-view.pane-item)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.7
convert-to-utf8, v0.2.4

# Dev
No dev packages
```

**Comment by xuan9** [comment]
Open the file first, then choose the menu item to convert. No such error happens.
